__BASE__: [
  '../coco.yaml',
  './hyp.scratch.p5.yaml',
]

per_batch_size: 16  # 16 * 8 = 128
img_size: 640
sync_bn: True
recompute: True
recompute_layers: 5

network:
  model_name: yolov7

  depth_multiple: 1.0  # model depth multiple
  width_multiple: 1.0  # layer channel multiple
  stride: [8, 16, 32]

  # anchors
  anchors:
    - [12,16, 19,36, 40,28]  # P3/8
    - [36,75, 76,55, 72,146]  # P4/16
    - [142,110, 192,243, 459,401]  # P5/32

  # yolov7 backbone
  backbone:
    # [from, number, module, args]
    [[-1, 1, ConvNormAct, [32, 3, 1]],  # 0

     [-1, 1, ConvNormAct, [64, 3, 2]],  # 1-P1/2
     [-1, 1, ConvNormAct, [64, 3, 1]],

     [-1, 1, ConvNormAct, [128, 3, 2]],  # 3-P2/4
     [-1, 1, ConvNormAct, [64, 1, 1]],
     [-2, 1, ConvNormAct, [64, 1, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [[-1, -3, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [256, 1, 1]],  # 11

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-3, 1, ConvNormAct, [128, 1, 1]], # 14
     [-1, 1, ConvNormAct, [128, 3, 2]],
     [[-1, -3], 1, Concat, [1]],  # 16-P3/8
     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-2, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -3, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [512, 1, 1]],

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-3, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 2]],
     [[-1, -3], 1, Concat, [1]],  # 29-P4/16
     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -3, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [1024, 1, 1]],

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [512, 1, 1]],
     [-3, 1, ConvNormAct, [512, 1, 1]],
     [-1, 1, ConvNormAct, [512, 3, 2]],
     [[-1, -3], 1, Concat, [1]],  # 42-P5/32
     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -3, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [1024, 1, 1]],  # 50
    ]

  # yolov7 head
  head:
    [[-1, 1, SPPCSPC, [512]], # 51

     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, Upsample, [None, 2, 'nearest']],
     [37, 1, ConvNormAct, [256, 1, 1]], # route backbone P4
     [[-1, -2], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [256, 1, 1]],

     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, Upsample, [None, 2, 'nearest']],
     [24, 1, ConvNormAct, [128, 1, 1]], # 66/ route backbone P3
     [[-1, -2], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-2, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [128, 1, 1]], # 75

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-3, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 2]],
     [[-1, -3, 63], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [256, 1, 1]], # 88

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-3, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 2]],
     [[-1, -3, 51], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [512, 1, 1]],
     [-2, 1, ConvNormAct, [512, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [512, 1, 1]], # 101

     [75, 1, RepConv, [256, 3, 1]],
     [88, 1, RepConv, [512, 3, 1]],
     [101, 1, RepConv, [1024, 3, 1]],

     [[102,103,104], 1, YOLOv7Head, [nc, anchors, stride]],   # Detect(P3, P4, P5)
    ]
