__BASE__: [
  '../coco.yaml',
  './hyp.scratch.p5.yaml',
]

per_batch_size: 12 # 12 * 8 = 96
img_size: 640
sync_bn: True
recompute: True
recompute_layers: 5

network:
  model_name: yolov7

  depth_multiple: 1.0  # model depth multiple
  width_multiple: 1.0  # layer channel multiple

  stride: [8, 16, 32]

  # anchors
  anchors:
    - [12,16, 19,36, 40,28]  # P3/8
    - [36,75, 76,55, 72,146]  # P4/16
    - [142,110, 192,243, 459,401]  # P5/32

  # yolov7 backbone
  backbone:
    # [from, number, module, args]
    [[-1, 1, ConvNormAct, [40, 3, 1]],  # 0

     [-1, 1, ConvNormAct, [80, 3, 2]],  # 1-P1/2
     [-1, 1, ConvNormAct, [80, 3, 1]],

     [-1, 1, ConvNormAct, [160, 3, 2]],  # 3-P2/4
     [-1, 1, ConvNormAct, [64, 1, 1]],
     [-2, 1, ConvNormAct, [64, 1, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [320, 1, 1]],  # 13

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [160, 1, 1]],
     [-3, 1, ConvNormAct, [160, 1, 1]],
     [-1, 1, ConvNormAct, [160, 3, 2]],
     [[-1, -3], 1, Concat, [1]],  # 18-P3/8
     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-2, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [640, 1, 1]],  # 28

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [320, 1, 1]],
     [-3, 1, ConvNormAct, [320, 1, 1]],
     [-1, 1, ConvNormAct, [320, 3, 2]],
     [[-1, -3], 1, Concat, [1]],  # 33-P4/16
     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [1280, 1, 1]],  # 43

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [640, 1, 1]],
     [-3, 1, ConvNormAct, [640, 1, 1]],
     [-1, 1, ConvNormAct, [640, 3, 2]],
     [[-1, -3], 1, Concat, [1]],  # 48-P5/32
     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [1280, 1, 1]],  # 58
    ]

  # yolov7 head
  head:
    [[-1, 1, SPPCSPC, [640]], # 59

     [-1, 1, ConvNormAct, [320, 1, 1]],
     [-1, 1, Upsample, [None, 2, 'nearest']],
     [43, 1, ConvNormAct, [320, 1, 1]], # route backbone P4
     [[-1, -2], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [320, 1, 1]], # 73

     [-1, 1, ConvNormAct, [160, 1, 1]],
     [-1, 1, Upsample, [None, 2, 'nearest']],
     [28, 1, ConvNormAct, [160, 1, 1]], # route backbone P3
     [[-1, -2], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-2, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [160, 1, 1]], # 87

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [160, 1, 1]],
     [-3, 1, ConvNormAct, [160, 1, 1]],
     [-1, 1, ConvNormAct, [160, 3, 2]],
     [[-1, -3, 73], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [320, 1, 1]], # 102

     [-1, 1, MP, []],
     [-1, 1, ConvNormAct, [320, 1, 1]],
     [-3, 1, ConvNormAct, [320, 1, 1]],
     [-1, 1, ConvNormAct, [320, 3, 2]],
     [[-1, -3, 59], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [512, 1, 1]],
     [-2, 1, ConvNormAct, [512, 1, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [[-1, -3, -5, -7, -8], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [640, 1, 1]], # 117

     [87, 1, ConvNormAct, [320, 3, 1]],
     [102, 1, ConvNormAct, [640, 3, 1]],
     [117, 1, ConvNormAct, [1280, 3, 1]],

     [[118,119,120], 1, YOLOv7Head, [nc, anchors, stride]],   # Detect(P3, P4, P5)
    ]
