__BASE__: [
  '../coco.yaml',
  './hyp.scratch.p6.yaml',
]

per_batch_size: 16 # 16 * 8 = 128
img_size: 1280
sync_bn: True

network:
  model_name: yolov7

  depth_multiple: 1.0  # model depth multiple
  width_multiple: 1.0  # layer channel multiple

  stride: [8, 16, 32, 64]

  # anchors
  anchors:
    - [ 19,27,  44,40,  38,94 ]  # P3/8
    - [ 96,68,  86,152,  180,137 ]  # P4/16
    - [ 140,301,  303,264,  238,542 ]  # P5/32
    - [ 436,615,  739,380,  925,792 ]  # P6/64

  # yolov7 backbone
  backbone:
    # [from, number, module, args],
    [[-1, 1, ReOrg, []],  # 0
     [-1, 1, ConvNormAct, [96, 3, 1]],  # 1-P1/2

     [-1, 1, DownC, [192]],  # 2-P2/4
     [-1, 1, ConvNormAct, [64, 1, 1]],
     [-2, 1, ConvNormAct, [64, 1, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [[-1, -3, -5, -7, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [192, 1, 1]],  # 14

     [-1, 1, DownC, [384]],  # 15-P3/8
     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-2, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -3, -5, -7, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [384, 1, 1]],  # 27

     [-1, 1, DownC, [768]],  # 28-P4/16
     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -3, -5, -7, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [768, 1, 1]],  # 40

     [-1, 1, DownC, [1152]],  # 41-P5/32
     [-1, 1, ConvNormAct, [384, 1, 1]],
     [-2, 1, ConvNormAct, [384, 1, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [-1, 1, ConvNormAct, [384, 3, 1]],
     [[-1, -3, -5, -7, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [1152, 1, 1]],  # 53

     [-1, 1, DownC, [1536]],  # 54-P6/64
     [-1, 1, ConvNormAct, [512, 1, 1]],
     [-2, 1, ConvNormAct, [512, 1, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [-1, 1, ConvNormAct, [512, 3, 1]],
     [[-1, -3, -5, -7, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [1536, 1, 1]],  # 66
    ]

  # yolov7 head
  head:
    [[-1, 1, SPPCSPC, [768]], # 67

     [-1, 1, ConvNormAct, [576, 1, 1]],
     [-1, 1, Upsample, [None, 2, 'nearest']],
     [53, 1, ConvNormAct, [576, 1, 1]], # route backbone P5
     [[-1, -2], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [384, 1, 1]],
     [-2, 1, ConvNormAct, [384, 1, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [576, 1, 1]], # 83

     [-1, 1, ConvNormAct, [384, 1, 1]],
     [-1, 1, Upsample, [None, 2, 'nearest']],
     [40, 1, ConvNormAct, [384, 1, 1]], # route backbone P4
     [[-1, -2], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [384, 1, 1]], # 99

     [-1, 1, ConvNormAct, [192, 1, 1]],
     [-1, 1, Upsample, [None, 2, 'nearest']],
     [27, 1, ConvNormAct, [192, 1, 1]], # route backbone P3
     [[-1, -2], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [128, 1, 1]],
     [-2, 1, ConvNormAct, [128, 1, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [-1, 1, ConvNormAct, [64, 3, 1]],
     [[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [192, 1, 1]], # 115

     [-1, 1, DownC, [384]],
     [[-1, 99], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [256, 1, 1]],
     [-2, 1, ConvNormAct, [256, 1, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [-1, 1, ConvNormAct, [128, 3, 1]],
     [[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [384, 1, 1]], # 129

     [-1, 1, DownC, [576]],
     [[-1, 83], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [384, 1, 1]],
     [-2, 1, ConvNormAct, [384, 1, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [-1, 1, ConvNormAct, [192, 3, 1]],
     [[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [576, 1, 1]], # 143

     [-1, 1, DownC, [768]],
     [[-1, 67], 1, Concat, [1]],

     [-1, 1, ConvNormAct, [512, 1, 1]],
     [-2, 1, ConvNormAct, [512, 1, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [-1, 1, ConvNormAct, [256, 3, 1]],
     [[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10], 1, Concat, [1]],
     [-1, 1, ConvNormAct, [768, 1, 1]], # 157

     [115, 1, ConvNormAct, [384, 3, 1]],
     [129, 1, ConvNormAct, [768, 3, 1]],
     [143, 1, ConvNormAct, [1152, 3, 1]],
     [157, 1, ConvNormAct, [1536, 3, 1]],

     [115, 1, ConvNormAct, [384, 3, 1]],
     [99, 1, ConvNormAct, [768, 3, 1]],
     [83, 1, ConvNormAct, [1152, 3, 1]],
     [67, 1, ConvNormAct, [1536, 3, 1]],

     [[158,159,160,161,162,163,164,165], 1, YOLOv7AuxHead, [nc, anchors, stride]],   # Detect(P3, P4, P5, P6)
    ]
