__BASE__: [
  '../coco.yaml',
  './hyp.scratch.high.yaml',
]

epochs: 500  # total train epochs
per_batch_size: 16  # 16 * 8 = 128
img_size: 640
iou_thres: 0.7
sync_bn: True
conf_free: True
max_call_depth: 3000
ms_loss_scaler: dynamic
ms_loss_scaler_value: 65536.0
clip_grad: True
overflow_still_update: False
opencv_threads_num: 0  # opencv: disable threading optimizations

network:
  model_name: yolov9
  nc: 80  # number of classes
  reg_max: 16

  stride: [8, 16, 32]
  depth_multiple: 1.0  # scales module repeats
  width_multiple: 1.0  # scales convolution channels

  # gelan backbone
  backbone:
    [
      # conv down
    [-1, 1, ConvNormAct, [16, 3, 2]],  # 0-P1/2

      # conv down
    [-1, 1, ConvNormAct, [32, 3, 2]],  # 1-P2/4

      # elan-1 block
    [-1, 1, ELAN1, [32, 32, 16]],  # 2

      # avg-conv down
    [-1, 1, AConv, [64]],  # 3-P3/8

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [64, 64, 32, 3]],  # 4

      # avg-conv down
    [-1, 1, AConv, [96]],  # 5-P4/16

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [96, 96, 48, 3]],  # 6

      # avg-conv down
    [-1, 1, AConv, [128]],  # 7-P5/32

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [128, 128, 64, 3]],  # 8
    ]

  # elan head
  head:
    [
      # elan-spp block
    [-1, 1, SPPELAN, [128, 64]],  # 9

      # up-concat merge
    [-1, 1, Upsample, [None, 2, 'nearest']],
    [[-1, 6], 1, Concat, [1]],  # cat backbone P4

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [96, 96, 48, 3]],  # 12

      # up-concat merge
    [-1, 1, Upsample, [None, 2, 'nearest']],
    [[-1, 4], 1, Concat, [1]],  # cat backbone P3

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [64, 64, 32, 3]],  # 15

      # avg-conv-down merge
    [-1, 1, AConv, [48]],
    [[-1, 12], 1, Concat, [1]],  # cat head P4

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [96, 96, 48, 3]],  # 18 (P4/16-medium)

      # avg-conv-down merge
    [-1, 1, AConv, [64]],
    [[-1, 9], 1, Concat, [1]],  # cat head P5

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [128, 128, 64, 3]],  # 21 (P5/32-large)

      # elan-spp block
    [8, 1, SPPELAN, [128, 64]],  # 22

      # up-concat merge
    [-1, 1, Upsample, [None, 2, 'nearest']],
    [[-1, 6], 1, Concat, [1]],  # cat backbone P4

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [96, 96, 48, 3]],  # 25

      # up-concat merge
    [-1, 1, Upsample, [None, 2, 'nearest']],
    [[-1, 4], 1, Concat, [1]],  # cat backbone P3

      # elan-2 block
    [-1, 1, RepNCSPELAN4, [64, 64, 32, 3]],  # 28

      # detect
    [[28, 25, 22, 15, 18, 21], 1, YOLOv9Head, [nc, reg_max, stride]],  # Detect(P3, P4, P5)
    ]
