site_name: MindYOLO Docs
site_url: https://mindspore-lab.github.io/mindyolo
repo_url: https://github.com/mindspore-lab/mindyolo
repo_name: mindspore-lab/mindyolo
copyright: Copyright &copy; 2022 - 2023 MindSpore Lab

nav:
  - Home: index.md
  - Installation: installation.md
  - Model Zoo:
      - Benchmark: modelzoo/benchmark.md
      - YOLOv3: modelzoo/yolov3.md
      - YOLOv4: modelzoo/yolov4.md
      - YOLOv5: modelzoo/yolov5.md
      - YOLOv7: modelzoo/yolov7.md
      - YOLOv8: modelzoo/yolov8.md
      - YOLOx: modelzoo/yolox.md
  - Tutorials:  # Learning Oriented
      - Quick Start: tutorials/quick_start.md
      - Configuration: tutorials/configuration.md
      - Augmentation: tutorials/data_augmentation.md
      - Finetune: tutorials/finetune.md
      - CloudBrain: tutorials/modelarts.md
      - Deployment: tutorials/deployment.md

  - Developer Guides:  # Problem Oriented
      - Data Preparation: how_to_guides/data_preparation.md
      - Write A New Model: how_to_guides/write_a_new_model.md
      - Callback: how_to_guides/callback.md
  - Reference:
      - Data: reference/data.md
#      - loss: reference/models.md
#      - models.layers: reference/models.layers.md
      - Models: reference/models.md
#      - optim: reference/optim.md
#      - scheduler: reference/scheduler.md
#      - utils: reference/utils.md
  - Notes:
      - Change Log: notes/changelog.md
      - Contributing: notes/contributing.md
      - Code of Conduct: notes/code_of_conduct.md
      - FAQ: notes/faq.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    # - navigation.instant  # see https://github.com/ultrabug/mkdocs-static-i18n/issues/62
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotations

markdown_extensions:
  # Officially Supported Extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - tables
  - toc:
      permalink: true
  - wikilinks
  # Third Party Extensions(Bundles, PyMdown Extensions)
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            # Headings
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: true
            # Members
            show_submodules: true
            # Docstrings
            docstring_section_style: spacy
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
        en:
          name: English
        zh:
          name: 中文
      nav_translations:
        zh:
          Home: 主页
          Installation: 安装
          Model Zoo: 模型仓库
          Tutorials: 教程
          Quick Start: 快速开始
          Configuration: 配置
          Finetune: 微调
          CloudBrain: 云上启动
          Deployment: 部署
          Notes: 说明
          Change Log: 更新日志
          Code of Conduct: 行为准则
          FAQ: 常见问题
          Developer Guides: 开发者指导
          Reference: 引用
          Augmentation: 数据增强
          Training: 训练流程解析
          Data Preparation: 数据准备
          Augmentation(custom): 自定义数据增强
          Write A New Model: 自定义模型
          Callback: 回调函数用法
          Data: 数据
          Models: 模型
          Contributing: 参与项目





extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:mindspore-lab@huawei.com
    - icon: fontawesome/brands/github
      link: https://github.com/mindspore-lab/mindyolo
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/mindsporelab